### ISSUE TITLE
[Todo] Add Guteberg CSS-like debugger for text

### ISSUE THREAD

**Issue by zaydek** [zaydek/prose#10]
Something like this:

```css
div {
  font: 16px/1.625 "BlinkMacSystemFont";
}

[grid\:single] {
	box-sizing: border-box !important;
	background-image:
		linear-gradient(to bottom,
			#00AAFF7F       1px, transparent                       0, transparent 0.8125rem,
			#00AAFF3F 0.8125rem, transparent calc(0.8125rem + 0.5px), transparent 1.6250rem
		) !important;
	background-size: 100% 1.625rem       !important;
	border-bottom: 1px solid transparent !important;
}

[grid\:double] {
  box-sizing: border-box !important;
  background-image:
    linear-gradient(to bottom,
      #00AAFF7F 1px                       , transparent 0                 , transparent calc(1*1.625rem/4),
      #00AAFF3F calc(1*1.625rem/4 + 0.5px), transparent calc(1*1.625rem/4), transparent calc(2*1.625rem/4),
      #00AAFFFF calc(2*1.625rem/4 + 0.5px), transparent calc(2*1.625rem/4), transparent calc(3*1.625rem/4),
      #00AAFF3F calc(3*1.625rem/4 + 0.5px), transparent calc(3*1.625rem/4), transparent calc(4*1.625rem/4)
    ) !important;
  background-size: 100% 1.625rem       !important;
  border-bottom: 1px solid transparent !important;
}
```

Via https://codepen.io/zaydek/pen/YzWveYz.
