### ISSUE TITLE
[Fixme] `overflow-x`

### ISSUE THREAD

**Issue by zaydek** [zaydek/prose#7]
There is some overflow-x bug visible in the demo and on Feather.

**Comment by zaydek** [comment]
This seems like a regression.

**Comment by zaydek** [comment]
Found the bug:

```scss
pre {
	@include no-macos-retina;

	margin: rem(24) rem(-16);
	padding: rem(12) rem(16);
	background-color: var(--gray-800);
	font: 400 $font-size-small-em / 1.6 $mono;
	color: var(--white);
	border-radius: 0;
	@media (min-width: $sm) {
		& {
			margin: rem(24) 0;
			padding: rem(12) rem(24);
			border-radius: rem(6);
		}
	}
}
```

Had the wrong values previously.
